// <auto-generated />
using System;
using DesafioBack.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioBack.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220901144254_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioBack.Domain.Entity.TaskTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("Tarefas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2022, 9, 1, 11, 42, 54, 386, DateTimeKind.Local).AddTicks(8155),
                            Descricao = "Teste de Descrição 1",
                            Titulo = "Titulo 1"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2022, 9, 1, 11, 42, 54, 387, DateTimeKind.Local).AddTicks(8528),
                            Descricao = "Teste de Descrição 2",
                            Titulo = "Titulo 2"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2022, 9, 1, 11, 42, 54, 387, DateTimeKind.Local).AddTicks(8547),
                            Descricao = "Teste de Descrição 3",
                            Titulo = "Titulo 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
